Feature/review module
ModernSoftwareDevelopement/taskusnow-api pull request #19
Opened 2023-11-15 08:46 UTC by apphyo99

New PR for review module.

2023-11-16 02:47 UTC, thetnaingtta reviewed
it looks good, but I think it is better to get latest develop and merge, and also add more tests to cover the code coverage for Sonar.

2023-11-16 02:47 UTC, thetnaingtta commented on src/app.ts
I think you haven't merged to the latest develop yet.

2023-11-16 08:21 UTC, apphyo99 commented on src/app.ts
yes, babe. Merged it now and updated again.

2023-11-16 09:45 UTC, thetnaingtta reviewed
Please add test for your module

2023-11-17 12:18 UTC, sithwin requested changes
Good Job! But unit tests are missing :)

2023-11-20 01:41 UTC, thetnaingtta approved these changes
Great Job!!!!!!!

2023-11-20 01:41 UTC, thetnaingtta commented on src/reviews/repos/createReview/impl/InMemoryCreateReviewRepositoryImpl.spec.ts
it would be better remove the extra line breaks , format the document with prettier

2023-11-20 01:41 UTC, thetnaingtta commented on src/reviews/repos/getReviewByUserId/impl/InMemoryGetReviewByUserIdRepositoryImpl.ts
I am not sure but I think this will work => return result ?? undefined;

2023-11-20 08:01 UTC, merged